/* 
  DO NOT EDIT THIS FILE
  Please do not modify files in the test directory.
  This can cause the tests to give incorrect results or fail, making it harder to identify and fix issues in the code.
  Make any necessary changes to the original file and re-run the tests to ensure they are still working correctly.
*/

const commandLineArguments = require("minimist")(process.argv.slice(2));
const readFile = require("./src/readFile");
const executeQuery = require("./src/executeQuery");

(async () => {
  try {
    const sql = await readFile(
      `${require("path").resolve(__dirname)}/seed.sql`
    );
    
    /**
     * Command : npm run seed:data --  --username= --password=
     * Note: To be executed with root permissions only
     * Reads the seed.sql file
     * Splits it with `;` to separate out individual queries
     * Executes individual queries against the DB.
     */
    let result;
    const { username, password } = commandLineArguments;
    if (sql.length > 0) {
      const queries = sql.split(";");
      for (const query of queries) {
        if (query.length > 1) {
          result = await executeQuery(query, username, password);
          console.log(result);
        }
      }
      console.log(`Completed executing seed data. You may now proceed with the tasks.`);
    }
  } catch (e) {
    console.error(e);
  }
})();
