/* 
  DO NOT EDIT THIS FILE
  Please do not modify files in the test directory.
  This can cause the tests to give incorrect results or fail, making it harder to identify and fix issues in the code.
  Make any necessary changes to the original file and re-run the tests to ensure they are still working correctly.
*/

let readFile = require("./readFile");
let executeQuery = require("./executeQuery");

(async () => {
  try {
    const sql = await readFile(
      `${require("path").resolve(__dirname)}/task3.sql`
    );

    let result;
    if (sql.length > 0) {
      result = await executeQuery(sql);
    }
    console.table(result);
  } catch (e) {
    console.error(e);
  }
})();

/**
 * Output
 
Name       |invoice_no|
-----------+----------+
John Dean  |jo993054  |
Alex Smith |al992897  |
Steve Hopes|st992487  |
John Dean  |jo992754  |
Alex Smith |al992697  |
Steve Hopes|st992587  |

 */
